<?php
/**
 * Tvcom
 * Author: TonyVu
 * Date: 10.01.2014
 * Description
 */
?>
<!-- Modal -->
<div class="modal fade" id="ajaxcontactModal" tabindex="-1" role="dialog" aria-labelledby="Ajax contact form">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
            <div class="row">
                <div class="col-xs-6">
                    <h4 class="modal-title" id="">CONTACT US</h4>
                </div>
                <div class="col-xs-6" style="text-align: right">
                      <div class="divspin"><i class="fa fa-spinner fa-spin fa-lg"></i></div>
                </div>
            </div>
      </div>
      <form action="<?php echo Mage::getBaseUrl() . 'contacts/index/post/' ?>" method="post" id="ajaxcontact-form">
          <div class="modal-body">          
            <p>Type your request.</p>
            <p><input name="contact[name]" id="name" class="input-text required-entry form-control" type="text" placeholder="Your Name"></p>
            <p><input name="contact[email]" id="email" class="input-text required-entry validate-email form-control" type="text" placeholder="Email"></p>
            <p><input name="contact[telephone]" id="telephone" class="input-text form-control" type="text" placeholder="Phone Number"></p>
            <p><textarea name="contact[comment]" id="comment" class="required-entry input-text form-control" rows="3" placeholder="Comment"></textarea></p>                
          </div>
          <div class="modal-footer">  
              <div class="row">
                  <div class="col-xs-6" style="text-align: left">
                        <p class="smscontact alert alert-success"></p>  
                  </div>
                  <div class="col-xs-6">
                        <button type="button" title="Submit" class="btnajaxcontact btn btn-success">Submit</button>
                        <button type="button" class="btncontact-cancel btn btn-default" data-dismiss="modal">Close</button>
                  </div>
              </div>
          </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->