<?php
/**
 * Tvcom
 * Author: TonyVu
 * Date: 10.01.2014
 * Description
 */
?>
<!-- Modal -->
<div class="modal fade" id="ajaxregisterModal" tabindex="-1" role="dialog" aria-labelledby="Ajax regiter form" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
            <div class="row">
                <div class="col-xs-6">
                    <h4 class="modal-title" id="">REGISTER ACCOUNT</h4>
                </div>
                <div class="col-xs-6" style="text-align: right">
                      <div class="divspin"><i class="fa fa-spinner fa-spin fa-lg"></i></div>
                </div>
            </div>
      </div>
      <form action="<?php echo Mage::getBaseUrl() . 'customer/account/createpost/' ?>" method="post" id="ajaxregister-form">
          <div class="modal-body">          
            <p>Type your details, then <span style="color:#e26703">enter</span>.</p>
            <div class="row">
                <div class="col-sm-6 col-xs-12 bottommargin">
                    <input type="text" id="firstname" name="register[firstname]" value="" title="First Name" class="form-control input-text required-entry" placeholder="First Name" />
                </div>
                <div class="col-sm-6 col-xs-12 bottommargin">
                    <input type="text" id="lastname" name="register[lastname]" value="" title="Last Name" class="form-control input-text required-entry" placeholder="Last Name" />
                </div>
            </div>
            
            <div class="row">
                <div class="col-sm-6 col-xs-12 bottommargin">
                    <input type="text" name="register[email]" id="email_address" value="" title="Email Address" class="form-control input-text validate-email required-entry" placeholder="Email" />
                </div>
                <div class="col-sm-6 col-xs-12 bottommargin">
                    <input type="checkbox" name="register[is_subscribed]" title="Sign Up for Newsletter" value="1" id="is_subscribed" class="checkbox" />Sign Up for Newsletter
                </div>
            </div>
            
            <div class="row">
                <div class="col-sm-6 bottommargin">
                    <input type="password" name="register[password]" id="password" title="Password" class="form-control input-text required-entry validate-password" placeholder="Password" />
                </div>
                <div class="col-sm-6">
                    <input type="password" name="register[confirmation]" title="Confirm Password" id="confirmation" class="form-control input-text required-entry validate-cpassword" placeholder="Confirm Password" />
                </div>
            </div>
          </div>
          <div class="modal-footer">  
              <div class="row">
                  <div class="col-xs-6" style="text-align: left">
                        <p class="smsregister alert alert-success"></p>  
                  </div>
                  <div class="col-xs-6">
                        <button type="button" title="Submit" class="btnajaxregister btn btn-success">Submit</button>
                  </div>
              </div>
          </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->