<?php
/**
 * Tvcom
 * Author: TonyVu
 * Date: 10.01.2014
 * Description
 */
?>
<!-- Modal -->
<div class="modal fade" id="ajaxloginModal" tabindex="-1" role="dialog" aria-labelledby="Ajax login form" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <div class="row">
              <div class="col-xs-6">
                <h4 class="modal-title" id="">LOGIN</h4>
              </div>
              <div class="col-xs-6" style="text-align: right">
                  <div class="divspin"><i class="fa fa-spinner fa-spin fa-lg"></i></div>
              </div>
          </div>
      </div>
      <form action="<?php echo Mage::getBaseUrl() . 'customer/account/login' ?>" method="post" id="ajaxlogin-form">
          <div class="modal-body">           
            <p>Type your email and password.</p>
            <p><input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email form-control" title="<?php echo $this->__('Email Address') ?>" placeholder="Email"/></p>
            <p><input type="password" name="login[password]" class="input-text required-entry validate-password form-control" id="pass" title="<?php echo $this->__('Password') ?>" placeholder="Password" /></p>
            <a href="<?php echo Mage::getBaseUrl() . 'customer/account/forgotpassword/' ?>"><?php echo $this->__('Forgot Your Password?') ?></a>
          </div>
          <div class="modal-footer">  
              <div class="row">
                  <div class="col-xs-6" style="text-align: left">
                        <p class="smslogin alert alert-success"></p>  
                  </div>
                  <div class="col-xs-6">
                        <button type="button" title="Login" class="btnajaxlogin btn btn-success">Login</button>
                  </div>
              </div>
          </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->