<?php
/**
 * Tvcom
 * Author: TonyVu
 * Date: 10.01.2014
 * Description
 */
?>
<div id="ajaxlogin">
    <?php if($this->helper('customer')->isLoggedIn() == 1): ?>
    <a href="<?php echo Mage::getBaseUrl() ?>/customer/account/logout/" title="Log Out">Log Out</a>
     <?php else: ?>   
        <button class="btn btn-danger" id="btnajaxlogin" data-toggle="modal" data-target="#ajaxloginModal">Login</button>
    <?php endif; ?>   
</div>

<!-- Modal -->
<div class="modal fade" id="ajaxloginModal" tabindex="-1" role="dialog" aria-labelledby="Ajax login form" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">LOGIN</h4>
      </div>
      <form action="<?php echo Mage::getBaseUrl() . 'customer/account/login' ?>" method="post" id="ajaxlogin-form">
          <div class="modal-body">                      
            <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
            <p><input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email form-control" title="<?php echo $this->__('Email Address') ?>" placeholder="Email"/></p>
            <p><input type="password" name="login[password]" class="input-text required-entry validate-password form-control" id="pass" title="<?php echo $this->__('Password') ?>" placeholder="Password" /></p>
            <p><a href="<?php echo Mage::getBaseUrl() . 'customer/account/forgotpassword/' ?>"><?php echo $this->__('Forgot Your Password?') ?></a></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="btnlogin">Login</button>
          </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
    
jQuery(document).ready(function() {   
    
        jQuery('#btnlogin').bind('click', function() {
            jQuery.ajax({
                url: jQuery('#ajaxlogin-form').attr('action'),
                type: 'post',
                data: jQuery('#ajaxlogin-form').serialize(),
                async: false,
                success: function(data) {               
                    json = eval("(" + data + ")");
                   // alert(json.user);
                    if (json.logined == 1){                                                                               
                        /* update the toplink */
                        jQuery('#toplink').html(json.toplink);
                        /* username */
                        jQuery('.welcome-msg').html('Welcome,' + json.user);                                                
                    }else{
                        alert('Your username/password are incorrect');
                    }
                },
                error: function() {
                    alert('There has been an error, please alert us immediately');
                }
            });
        });    
    
});

</script>