<?php
/* 
 * Authod       Tony Vu
 * Date         12.12.2013
 * Description  social network sharing     
 */
?>

<?php
// get the config
$facebook = Mage::getStoreConfig('setting/footer/facebook');
$twitter = Mage::getStoreConfig('setting/footer/twitter');
$youtube = Mage::getStoreConfig('setting/footer/youtube');
?>
<div id="divnetworkshare" class="">
    <?php if($facebook != '' || $twitter !=='' || $youtube !=''): ?>
        <p class='title'>Follow us</p>
    <?php endif; ?>
    
    <?php if($facebook != ''): ?>
        <a href="<?php echo $facebook ?>" target='_blank' alt="facebook"><i class="fa fa-facebook-square fa-3x"></i></a>
    <?php endif; ?>
    
    <?php if($twitter != ''): ?>    
        <a href="<?php echo $twitter ?>" target='_blank' alt="twitter"><i class="fa fa-twitter-square fa-3x"></i></a>
    <?php endif; ?>
        
    <?php if($youtube !=''): ?>    
        <a href="<?php echo $youtube ?>" target='_blank' alt="youtube"><i class="fa fa-youtube-square fa-3x"></i></a>
    <?php endif; ?>
</div>
