<?php
/* 
 * Authod       Tony Vu
 * Date         12.12.2013
 * Description  Product New Arrival Block
 */
?>

<h3>Best Selling Products</h3>    <!-- Prev/next controls -->
       <a class="jcarousel-prev">&lsaquo; Prev</a>
   | <span style="font-weight: bold">Slider</span> |
   <a class="jcarousel-next">Next &rsaquo;</a>  
<div style="padding: 10px 0;" class="row jcarousel"><!-- row 1 example data -->
    <ul>
        <li>
            <div>
            <a href="sony-vaio-vgn-txn27n-b-11-1-notebook-pc.html"><img class="product-img" src="<?php echo $this->getSkinUrl('images/media/best_selling_img01.jpg') ?>" alt="" /></a>
            <p><a href="sony-vaio-vgn-txn27n-b-11-1-notebook-pc.html">Sony VAIO VGN-TXN27N/B 11.1" Notebook PC</a></p>
            </div>
        </li> 
        
        <li>
            <div>
            <a href="nine-west-women-s-lucero-pump.html"><img class="product-img" src="<?php echo $this->getSkinUrl('images/media/best_selling_img02.jpg') ?>" alt="" /></a>
            <p><a href="nine-west-women-s-lucero-pump.html">Nine West Women's Lucero Pump</a></p>
            </div>
        </li>
        
        <li>
            <div>
                <a href="nine-west-women-s-lucero-pump.html"><img class="product-img" src="<?php echo $this->getSkinUrl('images/media/best_selling_img02.jpg') ?>" alt="" /></a>
                <p><a href="nine-west-women-s-lucero-pump.html">Nine West Women's Lucero Pump</a></p>
            </div>
        </li>
        
        <li>
            <div>
                <a href="nine-west-women-s-lucero-pump.html"><img class="product-img" src="<?php echo $this->getSkinUrl('images/media/best_selling_img02.jpg') ?>" alt="" /></a>
                <p><a href="nine-west-women-s-lucero-pump.html">Nine West Women's Lucero Pump</a></p>
            </div>
        </li>
    </ul>

</div>

<script>
jQuery(function() {
    // create instance
    jQuery('.jcarousel').jcarousel();
    
    jQuery('.jcarousel-prev').click(function() {
        jQuery('.jcarousel').jcarousel('scroll', '-=1');
    });

    jQuery('.jcarousel-next').click(function() {
        jQuery('.jcarousel').jcarousel('scroll', '+=1');
    });


});
</script>
    
    