<?php
/* 
 * Authod       Tony Vu
 * Date         24.12.2013
 * Description  Mega Menu 
 */
?>

<?php        
    // get storeconfig
     $is_Megamenu = Mage::getStoreConfig('yamm/setting/yes_no');
     // if Megamenu is yes
     if($is_Megamenu  == 1){ 
        $narbar_style = Mage::getStoreConfig('yamm/setting/navbar'); 
        if ($narbar_style ==''){
           // navbar-default is an option in the setting/header/navbar
           $narbar_style = 'navbar-default';
        } 
        
     $yam_logo_text = Mage::getStoreConfig('yamm/setting/logotext');    
?>

<div class="navbar yamm <?php echo $narbar_style ?>">
    <div class="container">
      <div class="navbar-header">
        <button type="button" data-toggle="collapse" data-target="#navbar-collapse-1" class="navbar-toggle">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <!-- company logo -->
        <?php if(Mage::getStoreConfig('yamm/setting/logo') != ''): ?>
            <a class="navbar-brand" href="<?php echo $this->getBaseUrl(); ?>"><img height="50px" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'logo/' . Mage::getStoreConfig('yamm/setting/logo') ?>" alt="<?php echo Mage::getStoreConfig('yamm/setting/logoalt') ?>"></a>
        <?php else: ?>
            <a href="#" class="navbar-brand"><?php echo $yam_logo_text ?></a>
        <?php endif; ?>
      </div>
      <div id="navbar-collapse-1" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <!-- Classic list -->
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Categories <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <!-- Content container to add padding -->
                <div class="yamm-categories yamm-content megamenu_cat_1">
                 <!-- banner for promotion -->                    
                 <?php if(Mage::getStoreConfig('yamm/category/ad') != null): ?>
                    <div class="row">
                        <a href="<?php echo Mage::getStoreConfig('yamm/category/link') ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'ad_banner/' . Mage::getStoreConfig('yamm/category/ad'); ?>" class="img-responsive" alt="<?php echo Mage::getStoreConfig('yamm/category/alt') ?>"></a>
                    </div>
                 <?php endif; ?>
                 <?php 
                    $categories = Mage::helper('mega/data')->getCatergorybyLevel(3);    
                    echo $categories;
                 ?>
                  <!-- show all categories -->
                  <div class="row showall" >
                      <a class="btn btn-default btnviewall">View all</a>
                  </div>     
                </div>
              </li>
            </ul>
          </li>
          <!-- Feature Products -->
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Feature Products<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <div class="yamm-content megamenu_cat_2">                                
                    <?php 
                        //get feature products from getstoreconfig
                        $product_sku_1 = trim(Mage::getStoreConfig('yamm/feature/product1'));
                        $product_sku_2 = trim(Mage::getStoreConfig('yamm/feature/product2'));
                        $product_sku_3 = trim(Mage::getStoreConfig('yamm/feature/product3'));
                        $product_sku_4 = trim(Mage::getStoreConfig('yamm/feature/product4'));                       
                        $arr_product_sku = array($product_sku_1, $product_sku_2, $product_sku_3, $product_sku_4) ;
                        
                        $feature_product_list = Mage::helper('mega/data')->getFeaturedProducts($arr_product_sku);    
                        echo $feature_product_list;
                    ?>
                <!-- banner for promotion -->   
                <!-- banner for promotion -->                    
                 <?php if(Mage::getStoreConfig('yamm/feature/ad') != null): ?>
                    <div class="row">
                        <a href="<?php echo Mage::getStoreConfig('yamm/feature/link') ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'ad_banner/' . Mage::getStoreConfig('yamm/feature/ad'); ?>" class="img-responsive" alt="<?php echo Mage::getStoreConfig('yamm/feature/alt') ?>"></a>
                    </div> 
                <?php endif;?>
                </div>
              </li>
            </ul>
          </li>           
          <!-- Sales -->
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Sales<b class="caret"></b></a>              
                <ul class="dropdown-menu">
                  <li>
                    <div class="yamm-content megamenu_cat_3 col-xs-12"> 
                        <div class='row'>
                            <?php if(Mage::getStoreConfig('yamm/sale/ad') != null): ?>
                                <div class='col-md-3 banner'>
                                    <a href="<?php echo Mage::getStoreConfig('yamm/sale/link') ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'ad_banner/' . Mage::getStoreConfig('yamm/sale/ad'); ?>" class="img-responsive" alt="<?php echo Mage::getStoreConfig('yamm/sale/alt') ?>"></a>
                                </div>
                            <?php endif; ?>
                            <div class='col-md-9 col-sm-12'>
                                <?php 
                                    //get feature products from getstoreconfig
                                    $product_sku_1 = trim(Mage::getStoreConfig('yamm/sale/product1'));
                                    $product_sku_2 = trim(Mage::getStoreConfig('yamm/sale/product2'));
                                    $product_sku_3 = trim(Mage::getStoreConfig('yamm/sale/product3'));
                                    $product_sku_4 = trim(Mage::getStoreConfig('yamm/sale/product4'));                       
                                    $arr_product_sku = array($product_sku_1, $product_sku_2, $product_sku_3, $product_sku_4) ;
                                    $sale_product_list = Mage::helper('mega/data')->getSaleProducts($arr_product_sku);                            
                                    echo $sale_product_list;
                                ?>
                            </div>
                        </div>
                    </div>
                  </li>
                </ul>
        </li>
      </div>
    </div>
</div>

<script type='text/javascript' defer>        
    jQuery('.yamm .dropdown-menu').click(function(e) {
       e.stopPropagation();
     });
 </script>
 
 <?php } ?>