<?php
/* 
 * Authod       Tony Vu
 * Date         24.12.2013
 * Description  Mega Menu 
 */
?>

<?php        
    // get storeconfig
     $is_Megamenu = Mage::getStoreConfig('yamm/setting/yes_no');
     // if Megamenu is yes
     if($is_Megamenu  == 1){ 
        $narbar_style = Mage::getStoreConfig('yamm/setting/navbar'); 
        if ($narbar_style ==''){
           // navbar-default is an option in the setting/header/navbar
           $narbar_style = 'navbar-default';
        } 
        
     $yam_logo_text = Mage::getStoreConfig('yamm/setting/logotext');    
?>

<div class="navbar yamm <?php echo $narbar_style ?>">
    <div class="container">
      <div class="navbar-header">
        <button type="button" data-toggle="collapse" data-target="#navbar-collapse-1" class="navbar-toggle">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <!-- company logo -->
        <?php if(Mage::getStoreConfig('yamm/setting/logo') != ''): ?>
            <a class="navbar-brand" href="<?php echo $this->getBaseUrl(); ?>"><img height="50px" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'logo/' . Mage::getStoreConfig('yamm/setting/logo') ?>" alt="<?php echo Mage::getStoreConfig('yamm/setting/logoalt') ?>"></a>
        <?php else: ?>
            <a href="#" class="navbar-brand"><?php echo $yam_logo_text ?></a>
        <?php endif; ?>
      </div>
      <div id="navbar-collapse-1" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <!-- Classic list -->
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Categories <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <!-- Content container to add padding -->
                <div class="yamm-categories yamm-content">
                 <!-- banner for promotion -->   
                 <div class="row">
                     <a href="" alt=""><img data-src="holder.js/650x50" class="img-responsive" alt="..."></a>
                 </div>
                 <?php 
                    $categories = Mage::helper('mega/data')->getCatergorybyLevel(3);    
                    echo $categories;
                 ?>
                  <!-- show all categories -->
                  <div class="row showall" >
                      <p><a href="">View all</a></p>
                  </div>     
                </div>
              </li>
            </ul>
          </li>
          <!-- New Arrival-->
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">New Arrival<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <div class="yamm-content">
                      <div class="row">
                      <div class="col-md-3 col-sm-6 col-xs-12">
                      <div class="thumbnail">
                      <img data-src="holder.js/200x200" alt="...">
                      <div class="caption">
                      <h3>Thumbnail label</h3>
                      <p>...</p>
                      <p><a href="#" class="btn btn-default" role="button">Button</a></p>
                      </div>
                      </div>
                      </div>

                      <div class="col-md-3 col-sm-6 col-xs-12">
                      <div class="thumbnail">
                      <img data-src="holder.js/200x200" alt="...">
                      <div class="caption">
                      <h3>Thumbnail label</h3>
                      <p>...</p>
                      <p><a href="#" class="btn btn-default" role="button">Button</a></p>
                      </div>
                      </div>
                      </div>    

                       <div class="col-md-3 col-sm-6 col-xs-12">
                      <div class="thumbnail">
                      <img data-src="holder.js/200x200" alt="...">
                      <div class="caption">
                      <h3>Thumbnail label</h3>
                      <p>...</p>
                      <p><a href="#" class="btn btn-default" role="button">Button</a></p>
                      </div>
                      </div>
                      </div>

                           <div class="col-md-3 col-sm-6 col-xs-12">
                      <div class="thumbnail">
                      <img data-src="holder.js/200x200" alt="...">
                      <div class="caption">
                      <h3>Thumbnail label</h3>
                      <p>...</p>
                      <p><a href="#" class="btn btn-default" role="button">Button</a></p>
                      </div>
                      </div>
                      </div>


                      </div>

                      <!-- show all New Arrivals -->
                  <div class="row">
                      <p style="text-align: right"><a href="">View all</a></p>
                  </div> 
                </div>
              </li>
            </ul>
          </li>           
          <!-- Sales -->
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Sales<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li>
                    <div class="yamm-content">
                      <ul class="media-list">
                        <li class="media"><a href="#" class="pull-right"><img src="http://placekitten.com/64/64/" alt="64x64" class="media-object"></a>
                          <div class="media-body">
                            <h4 class="media-heading">Media heading</h4>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante.
                          </div>
                        </li>
                        <li class="media"><a href="#" class="pull-right"><img src="http://placekitten.com/64/64/" alt="64x64" class="media-object"></a>
                          <div class="media-body">
                            <h4 class="media-heading">Media heading</h4>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque.
                          </div>
                        </li>
                      </ul>
                    </div>
                  </li>
                </ul>
        </li>
      </div>
    </div>
</div>

<script type='text/javascript' defer>     
    // remove default nav
    
    jQuery('#default-nav').remove();
    
    jQuery('.yamm .dropdown-menu').click(function(e) {
       e.stopPropagation();
     });
 </script>
 
 <?php } ?>