<?php
/**
 * Bootstrap Carousel
 * Tony Vu
 * 29.01.2014
 */
?>
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="margin-bottom: 20px;">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active"> <!-- product 1 -->
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'carousel/shoes/1.jpg' ; ?>" alt="...">
      <div class="carousel-caption">
        shoe 1
      </div>
    </div>
    
    <div class="item"> <!-- product 2 -->
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'carousel/shoes/2.jpg' ; ?>" alt="...">
      <div class="carousel-caption">
        shoe 2
      </div>
     </div>
      
     <div class="item">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'carousel/shoes/3.jpg' ; ?>" alt="...">
      <div class="carousel-caption">
        shoe 3
      </div>
    </div>
      
     <div class="item">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'carousel/shoes/4.jpg' ; ?>" alt="...">
      <div class="carousel-caption">
        show 1
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>